name: Deploy Backend to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update Backend
        shell: cmd
        run: |
          cd /d G:\qbackend\backend_mssql
          git fetch origin
          git reset --hard origin/main
          call npm install